version: "3.9"

services:

  flask:
    build:
      context: app
    scale: 3
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    ports:
      - "80:80"
    networks:
      - backend
      - default

networks:
  backend:
    driver: bridge
  


